name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container: pltamy/1lab:latest

    env:
      mailmap: ${{ secrets.MAILMAP }}

    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Shakefile version
        run: sha256sum /bin/1lab-shake | cut -d' ' -f1 > .shake-version

      - name: Cache _build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: _build
          key: shake-${{ hashFiles('.shake-version' )}}

      - name: Build 🛠️
        run: |
          echo "$mailmap" > .mailmap
          ln -sf $NODE_DEPS_PATH .
          git config --global --add safe.directory /__w/1lab/1lab
          1lab-shake all -j
          ./support/make-site.sh

      - name: Archive site 📦
        run: |
          tar \
            --dereference --hard-dereference \
            --directory _build/html \
            -cvf archive.tar \
            .

      - name: Upload site ⬆️
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: archive.tar
          retention-days: 1

  deploy:
    needs: build
    if: ${{ github.ref_name == 'main' }}

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy 🚀
        id: deployment
        uses: actions/deploy-pages@v1
