name: Build 1Lab
on: [push, pull_request]
jobs:
  container:
    runs-on: ubuntu-latest
    container: pltamy/1lab:latest
    steps:
      - run: |
          export PATH=/root/.local/bin:$PATH
          which 1lab-shake
          1lab-shake all -j
        name: Type check and build
