name: Build 1Lab
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container: pltamy/1lab:latest
    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v2

      - name: Build 🛠️
        run: |
          export PATH=/root/.local/bin:$PATH
          1lab-shake all -j
          ./support/make-site.sh

      - name: Deploy 🚀
        if: ${{ github.ref_name == 'main' }}
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: _build/site